version: "3.7"
# In Progress
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - wb-db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=wiredbeauty
      - POSTGRES_USER=wiredbeauty
      - POSTGRES_PASSWORD=wiredbeauty

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

  web:
    image: nginx:1.19.8-alpine
    volumes:
      - ./api:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - "8000:80"

  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    image: wb-php
    working_dir: /var/www
    volumes:
      - ./api:/var/www

  client:
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    image: wb-client
    working_dir: /home/node/app
    depends_on:
      - web
    environment:
      - NODE_ENV=development
    ports:
      - "80:3000"
    volumes:
      - ./client:/home/node/app

volumes:
  wb-db: {}
