version: "3.7"
# In Progress
services:
  #Voir pour Traefik ?
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - wb-db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=wiredbeauty
      - POSTGRES_USER=wiredbeauty
      - POSTGRES_PASSWORD=wiredbeauty
  web:
    image: nginx:1.19.8-alpine
    volumes:
      - ./api:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - "9000:80"
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    dns:
      - 172.17.0.1
      - 8.8.8.8
      - 8.8.4.4
    image: wb-php
    working_dir: /var/www
    volumes:
      - ./api:/var/www
  client:
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    image: wb-client
    working_dir: /home/node/app
    depends_on:
      - web
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/node/app
    command: bash -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"
volumes:
  wb-db: {}
